-- =================================================================================================
-- OLIST E-COMMERCE COHORT RETENTION ANALYSIS - COMPLETE MASTER FILE
-- Author: Ashish Dongre | Portfolio Project for Data Analyst Role
-- Purpose: Analyze customer retention behavior using pure SQL on the Olist dataset
-- =================================================================================================

-- -----------------------------------------------------------------------------
-- Initialize workspace
-- -----------------------------------------------------------------------------
SHOW DATABASES;
USE olist_data;

-- -----------------------------------------------------------------------------
-- SECTION 1: Delivery Overview
-- Purpose: Business health check - percentage of orders successfully delivered
-- -----------------------------------------------------------------------------
WITH order_summary AS (
    SELECT 
        COUNT(*) AS total_orders,
        SUM(CASE WHEN order_status = 'delivered' THEN 1 ELSE 0 END) AS delivered_orders
    FROM orders
)
SELECT 
    total_orders,
    delivered_orders,
    ROUND(100.0 * delivered_orders / NULLIF(total_orders, 0), 2) AS delivery_success_rate_pct
FROM order_summary;

-- -----------------------------------------------------------------------------
-- SECTION 2: Master Cohort Pipeline
-- Purpose:
-- 1. Build one clean order-level base table for delivered orders
-- 2. Assign each customer to a cohort month based on first delivered purchase
-- 3. Track customer activity across later months
-- 4. Reuse the same pipeline for business summary and final cohort matrix
-- -----------------------------------------------------------------------------

WITH base_orders AS (
    -- One row per delivered order
    SELECT 
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        DATE(DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m-01')) AS order_month,
        SUM(oi.price + oi.freight_value) AS total_order_value
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp
),

cohorts AS (
    -- First delivered purchase month for each customer
    SELECT
        customer_unique_id,
        MIN(order_month) AS cohort_month,
        MIN(order_purchase_timestamp) AS first_purchase_date
    FROM base_orders
    GROUP BY customer_unique_id
),

cohort_activity AS (
    -- All delivered order activity tagged to customer cohort month
    SELECT
        b.customer_unique_id,
        b.order_id,
        b.order_month,
        b.total_order_value,
        c.cohort_month,
        TIMESTAMPDIFF(MONTH, c.cohort_month, b.order_month) AS month_number
    FROM base_orders b
    JOIN cohorts c
        ON b.customer_unique_id = c.customer_unique_id
),

retention_counts AS (
    -- Customer and order activity by cohort-month
    SELECT
        cohort_month,
        month_number,
        COUNT(DISTINCT customer_unique_id) AS customer_count,
        COUNT(DISTINCT order_id) AS total_orders,
        SUM(total_order_value) AS cohort_month_revenue
    FROM cohort_activity
    GROUP BY
        cohort_month,
        month_number
),

cohort_sizes AS (
    -- Baseline size of each cohort
    SELECT
        cohort_month,
        COUNT(*) AS cohort_size
    FROM cohorts
    GROUP BY cohort_month
),

cohort_revenue AS (
    -- Total delivered revenue generated by each cohort across all observed months
    SELECT
        c.cohort_month,
        SUM(b.total_order_value) AS cohort_lifetime_revenue
    FROM base_orders b
    JOIN cohorts c
        ON b.customer_unique_id = c.customer_unique_id
    GROUP BY c.cohort_month
)

-- -----------------------------------------------------------------------------
-- SECTION 3: Master Cohort Business Summary
-- Purpose: Summary output for business understanding
-- -----------------------------------------------------------------------------
SELECT
    rc.cohort_month,
    rc.month_number,
    rc.customer_count,
    rc.total_orders,
    rc.cohort_month_revenue,
    cs.cohort_size,
    cr.cohort_lifetime_revenue,
    ROUND(100.0 * rc.customer_count / NULLIF(cs.cohort_size, 0), 2) AS retention_rate_pct,
    ROUND(100.0 - (100.0 * rc.customer_count / NULLIF(cs.cohort_size, 0)), 2) AS churn_rate_pct,
    ROUND(100.0 * rc.cohort_month_revenue / NULLIF(cr.cohort_lifetime_revenue, 0), 2) AS revenue_share_pct
FROM retention_counts rc
JOIN cohort_sizes cs
    ON rc.cohort_month = cs.cohort_month
JOIN cohort_revenue cr
    ON rc.cohort_month = cr.cohort_month
ORDER BY
    rc.cohort_month,
    rc.month_number;

-- -----------------------------------------------------------------------------
-- SECTION 4: Final Complete Cohort Retention Matrix
-- Purpose: Build a full cohort-month grid including zero-activity months
-- Output:
-- cohort_month | month_number | customer_count | cohort_size | retention_rate_pct | churn_rate_pct
-- -----------------------------------------------------------------------------

WITH RECURSIVE base_orders AS (
    -- One row per customer per active month from delivered orders
    SELECT
        c.customer_unique_id,
        DATE(DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m-01')) AS order_month
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY
        c.customer_unique_id,
        DATE(DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m-01'))
),

cohorts AS (
    -- First active month for each customer
    SELECT
        customer_unique_id,
        MIN(order_month) AS cohort_month
    FROM base_orders
    GROUP BY customer_unique_id
),

cohort_activity AS (
    -- Monthly activity distance from cohort month
    SELECT
        b.customer_unique_id,
        c.cohort_month,
        b.order_month,
        TIMESTAMPDIFF(MONTH, c.cohort_month, b.order_month) AS month_number
    FROM base_orders b
    JOIN cohorts c
        ON b.customer_unique_id = c.customer_unique_id
),

retention_counts AS (
    -- Active customers observed in each cohort-month
    SELECT
        cohort_month,
        month_number,
        COUNT(DISTINCT customer_unique_id) AS customer_count
    FROM cohort_activity
    GROUP BY
        cohort_month,
        month_number
),

cohort_sizes AS (
    -- Size of each cohort at month 0
    SELECT
        cohort_month,
        COUNT(*) AS cohort_size
    FROM cohorts
    GROUP BY cohort_month
),

cohort_list AS (
    SELECT DISTINCT cohort_month
    FROM cohorts
),

max_month AS (
    SELECT MAX(month_number) AS max_month_number
    FROM cohort_activity
),

months AS (
    SELECT 0 AS month_number
    UNION ALL
    SELECT month_number + 1
    FROM months
    WHERE month_number < (SELECT max_month_number FROM max_month)
),

final_retention AS (
    -- Full cohort-month grid with zero-filled missing months
    SELECT
        cl.cohort_month,
        m.month_number,
        COALESCE(r.customer_count, 0) AS customer_count,
        cs.cohort_size
    FROM cohort_list cl
    CROSS JOIN months m
    JOIN cohort_sizes cs
        ON cl.cohort_month = cs.cohort_month
    LEFT JOIN retention_counts r
        ON cl.cohort_month = r.cohort_month
       AND m.month_number = r.month_number
)

SELECT
    cohort_month,
    month_number,
    customer_count,
    cohort_size,
    ROUND(100.0 * customer_count / NULLIF(cohort_size, 0), 2) AS retention_rate_pct,
    ROUND(100.0 - (100.0 * customer_count / NULLIF(cohort_size, 0)), 2) AS churn_rate_pct
FROM final_retention
ORDER BY
    cohort_month,
    month_number;